In [ ]:
import numpy as np

# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)

print("\nCoefficient Matrix (A):")
print(A)

print("\nRight-hand Side Vector (b):")
print(b)

Generated 3x4 Matrix:
[[ 5  1  2 10]
 [11  7  9  9]
 [14  8 18 13]]

Coefficient Matrix (A):
[[ 5  1  2]
 [11  7  9]
 [14  8 18]]

Right-hand Side Vector (b):
[10  9 13]


In [ ]:
# Step 2: Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")


Solution using Matrix Inverse Method:
[ 2.56741573 -2.58988764 -0.12359551]


In [ ]:

# Step 3: Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Solve using Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)


Solution using Gaussian Elimination (NumPy):
[ 2.56741573 -2.58988764 -0.12359551]


In [ ]:
# Step 4: Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and x
print("\nVerification (Ax = b):")
print(b_check)


Verification (Ax = b):
[10.  9. 13.]
